import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics Course
  courseSidebar: [
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Physical AI and Humanoid Robotics',
      items: [
        'chapters/chapter-01/lesson-01',
        'chapters/chapter-01/lesson-02',
        'chapters/chapter-01/lesson-03',
        'chapters/chapter-01/lesson-04'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Fundamentals of Robotics and AI',
      items: [
        'chapters/chapter-02/lesson-05',
        'chapters/chapter-02/lesson-06',
        'chapters/chapter-02/lesson-07',
        'chapters/chapter-02/lesson-08'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Perception Systems for Humanoid Robots',
      items: [
        'chapters/chapter-03/lesson-09',
        'chapters/chapter-03/lesson-10',
        'chapters/chapter-03/lesson-11',
        'chapters/chapter-03/lesson-12'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Motion Planning and Control',
      items: [
        'chapters/chapter-04/lesson-13',
        'chapters/chapter-04/lesson-14',
        'chapters/chapter-04/lesson-15',
        'chapters/chapter-04/lesson-16'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 5: Human-Robot Interaction (HRI)',
      items: [
        'chapters/chapter-05/lesson-17',
        'chapters/chapter-05/lesson-18',
        'chapters/chapter-05/lesson-19',
        'chapters/chapter-05/lesson-20'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 6: Learning and Adaptation in Physical AI',
      items: [
        'chapters/chapter-06/lesson-21',
        'chapters/chapter-06/lesson-22',
        'chapters/chapter-06/lesson-23',
        'chapters/chapter-06/lesson-24'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 7: Cognitive Architecture for Humanoids',
      items: [
        'chapters/chapter-07/lesson-25',
        'chapters/chapter-07/lesson-26',
        'chapters/chapter-07/lesson-27',
        'chapters/chapter-07/lesson-28'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 8: Embodied AI and World Modeling',
      items: [
        'chapters/chapter-08/lesson-29',
        'chapters/chapter-08/lesson-30',
        'chapters/chapter-08/lesson-31',
        'chapters/chapter-08/lesson-32'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 9: Advanced Control Systems',
      items: [
        'chapters/chapter-09/lesson-33',
        'chapters/chapter-09/lesson-34',
        'chapters/chapter-09/lesson-35',
        'chapters/chapter-09/lesson-36'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 10: Applications and Case Studies',
      items: [
        'chapters/chapter-10/lesson-37',
        'chapters/chapter-10/lesson-38',
        'chapters/chapter-10/lesson-39',
        'chapters/chapter-10/lesson-40'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 11: Development Challenges and Solutions',
      items: [
        'chapters/chapter-11/lesson-41',
        'chapters/chapter-11/lesson-42',
        'chapters/chapter-11/lesson-43',
        'chapters/chapter-11/lesson-44'
      ],
    },
    {
      type: 'category',
      label: 'Chapter 12: Capstone Project - Building a Humanoid Robot',
      items: [
        'chapters/chapter-12/lesson-45',
        'chapters/chapter-12/lesson-46',
        'chapters/chapter-12/lesson-47',
        'chapters/chapter-12/lesson-48'
      ],
    },
  ],
};

export default sidebars;
